### ISSUE TITLE
Layman manual for adding overlay missing an option

### ISSUE THREAD

**Issue by programmador** [rindeal/rindeal-ebuild-repo#222]
Some time ago `layman -S` command started blaming that rindeal repo is not accessible anymore.
Maybe it was in gentoo overlays list before and now it's absent (at least layman -L doesn't show this repo). I don't know why. Anyway I couldn't add it manually by xml file like it's written in readme. `-f` option helped: `layman -o 'https://ebuilds.janchren.eu/repos/rindeal/repositories.xml' -f -a rindeal`

**Comment by rindeal** [comment]
Yes, they removed it from their list about 4 months ago, since I was unwilling to transfer copyright of my ebuilds to them. You can read more about that incident [here](https://github.com/gentoo/gentoo/pull/5557). However, the layman now requires the `-f` option indeed as it's not falling back to re-fetching the remote file in case its cached local copy wasn't found. I'll add that to the README. Thanks.

**Comment by programmador** [comment]
you're wellcome
