### ISSUE TITLE
dev-util/gdbus-codegen-2.99 ebuild does not create gdbus-codegen in /usr/bin

### ISSUE THREAD

**Issue by gh2k** [rindeal/rindeal-ebuild-repo#228]
Steps to reproduce:
```
emerge -1 =dev-util/gdbus-codegen-2.99::rindeal
ls -l /usr/bin/gdbus-codegen
ls: cannot access '/usr/bin/gdbus-codegen': No such file or directory
```
vs.
```
emerge -1 =dev-util/gdbus-codegen-2.52.3::gentoo
ls -l /usr/bin/gdbus-codegen
lrwxrwxrwx 1 root root 31 Mar 28 14:49 /usr/bin/gdbus-codegen -> ../lib/python-exec/python-exec2
```
Obviously this causes build failures in a number of subsequent builds.

**Comment by rindeal** [comment]
yes, that's the intended behaviour. See, gdbus-codegen is a part of glib, but for some non-obvious reason, Gentoo devs decided that it would be a good idea to extract it from the glib package into a separate package. So by using gentoo packages you're building gdbus-codegen twice, but in the glib package it's being deleted before installation. I didn't go that way in my glib package and I just install everything at once. But since many gentoo packages depend explicitly on gdbus-codegen package I had to create a virtual gdbus-codegen package in order to satisfy them. So in order for things to work you need to either use solely gentoo's glib+gdbus-codegen packages or solely mine. I might add notices into emerge logs though, in order to make this clear, because in Portage it's not possible to specify dependency on a package from a specific repository.

**Comment by rindeal** [comment]
So, I have made some measures to facilitate this problem and prevent such problems from occurring in the future. Namely:

#### 1. mask-alt-pkgs
https://github.com/rindeal/rindeal-ebuild-repo/commit/cf1f1e675d59f2f3b3d324c77d722f9e60de93df, https://github.com/rindeal/rindeal-ebuild-repo/commit/47222fe941cb61956b674a69afb3a97a32849bcc

I've created a `package.mask` list which masks all gentoo packages that are both in my repository and gentoo repository, and a script which creates links to those masks. By using this solution any mixing of my packages with gentoo packages is prevented.

#### 2. glib stabilization
https://github.com/rindeal/rindeal-ebuild-repo/commit/8caf805449ad6d52c908e0c8a0c73c0b6ca7d1ae

I've "stabilized" glib in order to satisfy "stable" gentoo packages which depend on "stable" glib. Thus portage will now consider my glib package as a valid dependency.

#### 3. gdbus-codegen RDEPEND + ewarn
https://github.com/rindeal/rindeal-ebuild-repo/commit/606facfa39b7b967348d43284fc54362975372cd

I've changed codegen's dep on glib from PDEPEND to RDEPEND to make glib a hard dependency and thus preventing rare issues when a package depending on codegen would start compiling before glib finished therefore causing a build error.

I've also added the aforementioned warning when installing my codegen package without mine glib package.
